### PR TITLE
Readme patches - pwnsdx

### PR DESCRIPTION
**Pull request by hephaest0s**
Thanks pwnsdx.

I chose not to include the banner because it depicts a violent, predatory animal. We are the mice, not the cat.

### CODE REVIEW

**Comment by pwnsdx** [comment]
Oh I see, I could put a mice instead. haha

(disgard my recent message "What about the banner?")

**Comment by pwnsdx** [comment]
By the way I don't see the thing like this. From my point of view, the violent animal is not you. It is the adversary who want your informations.

**Comment by hephaest0s** [comment]
Yes, That interpretation came to me later. Still would prefer to avoid the beast.

**Comment by pwnsdx** [comment]
Understood

**Pull request merged**
