### PR TITLE
USB_functionality

### PR DESCRIPTION
**Pull request by AddyM**

### CODE REVIEW

**Comment by pwnsdx** [comment]
?

**Comment by Charlesleonius** [comment]
...?

**Comment by hephaest0s** [comment]
?

**Comment by Zaxscdvf** [comment]
?

**Comment by pwnsdx** [comment]
`while(1) { print('?') }`

**Comment by AddyM** [comment]
Hi

**Comment by pwnsdx** [comment]
Hello, nice to meet you

**Pull request closed without merging**
