### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JayMaree**
Added the background cmdlet

### CODE REVIEW

**Comment by hephaest0s** [comment]
I actually wouldn't want to advertise this method. I think it becomes more difficult this way to halt the script if you decide to put in a legitimate usb.

**Comment by pwnsdx** [comment]
```I actually wouldn't want to advertise this method. I think it becomes more difficult this way to halt the script if you decide to put in a legitimate usb.````

I think it's pretty simple:

> killall python

haha

**Comment by hephaest0s** [comment]
Yes, but what other python processes do you have running?

**Comment by pwnsdx** [comment]
my "haha" was referring to it ^^

**Pull request closed without merging**
